name = "okym-fam-line-gpt"
main = "src/index.ts"
compatibility_date = "2023-04-14"

kv_namespaces = [
  { binding = "LINE_GPT_KV", id = "d72a68083cc24da9a720c84e1f0fa804" }
]


[[queues.producers]]
queue = "cloudflare-linebot-chatgpt-api-queue"
binding = "QUEUE"

[[queues.consumers]]
queue = "cloudflare-linebot-chatgpt-api-queue"
max_batch_size = 10
max_batch_timeout = 1

